# Generated by Django 2.1.1 on 2018-09-20 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['date_creation']},
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='shops.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('userId', 'item_id')},
        ),
    ]
